version: '3'

volumes:
  pgsql_data: {}
  nodejs_data: {}

services:
  postgresql:
    image: postgres:17.5-alpine3.22
    container_name: schola_blog_postgresql
    #ports:
    #  - "$POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT"
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - pgsql_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DATABASE"]
      interval: 1s
      timeout: 5s
      retries: 10
  node:
    image: node:24-slim
    container_name: schola_blog_node
    #depends_on:
    #  - postgresql
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    restart: always
    build: node_image
    #command: run_app.sh
    command: npm start
    volumes:
      - ./app:/opt/app